[package]
name = "rs-reflector-client"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-client = "0.3.3"
stellar-strkey = "0.0.11"
thiserror = "2.0.7"

[dev-dependencies]
tokio = { version = "1.42", features = ["test-util", "rt", "macros"] }
